version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/usr/local/vufind/
    depends_on:
      - mysql
      - solr
  mysql:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=vufind
    ports:
      - "3306:3306"
    volumes:
      - ./module/VuFind/sql/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
  solr:
    image: solr:6.4.2
    ports:
      - "8983:8983"
    volumes:
      - ./solr/vufind:/opt/solr/server/solr/mycores
      - ./solr/docker/dev_link_vendor.sh:/docker-entrypoint-initdb.d/dev_link_vendor.sh