---
# This file contains search specifications used by the reserves module; for details
# on the workings of this file, see the comments in searchspecs.yaml.
#-----------------------------------------------------------------------------------

AllFields:
  DismaxFields:
    - course^400
    - instructor^400
    - department^200
  QueryFields:
    - course:
      - [onephrase, 1000]
      - [and, 750]
      - [or, 10] 
    - instructor:
      - [onephrase, 1000]
      - [and, 750]
      - [or, 10] 
    - department:
      - [onephrase, 1000]
      - [and, 750]
      - [or, 10]
Instructor:
  DismaxFields:
    - instructor^400
  QueryFields:
    - instructor:
      - [onephrase, 1000]
      - [and, 750]
      - [or, 10] 
Course:
  DismaxFields:
    - course^400
  QueryFields:
    - course:
      - [onephrase, 1000]
      - [and, 750]
      - [or, 10]   
Department:
  DismaxFields:
    - department^400
  QueryFields:
    - department:
      - [onephrase, 1000]
      - [and, 750]
      - [or, 10]
